FROM node:12-alpine

WORKDIR /tmp/build

ENV HOST 0.0.0.0

COPY . . 

RUN cd /tmp/build

RUN yarn install

RUN yarn generate

RUN mkdir -p /var/acompanha_legis/www/

RUN cp -r dist/* /var/acompanha_legis/www/
