import { API_URLS, BASE_URL } from "@/api";

export enum URL_COMPLEMENT {
    ID_SUCCESS = 1,
    ID_NOT_FOUND = 2,
    ID_UNKNOWN_ERROR = 3,
}

export enum DEPUTADOS {
    SUCCESS = BASE_URL + API_URLS.DEPUTADOS + "/" + URL_COMPLEMENT.ID_SUCCESS,
    NOT_FOUND = BASE_URL + API_URLS.DEPUTADOS + "/" + URL_COMPLEMENT.ID_NOT_FOUND,
    UNKNOWN_ERROR = BASE_URL + API_URLS.DEPUTADOS + "/" + URL_COMPLEMENT.ID_UNKNOWN_ERROR,
}