import { API_URLS, BASE_URL } from "@/api";

export enum URL_COMPLEMENT_NUMBER {
    ID_SUCCESS = 1,
    ID_NOT_FOUND = 2,
    ID_UNKNOWN_ERROR = 3,
}

export enum DEPUTADOS {
    SUCCESS = BASE_URL + API_URLS.DEPUTADOS + "/" + URL_COMPLEMENT_NUMBER.ID_SUCCESS,
    NOT_FOUND = BASE_URL + API_URLS.DEPUTADOS + "/" + URL_COMPLEMENT_NUMBER.ID_NOT_FOUND,
    UNKNOWN_ERROR = BASE_URL + API_URLS.DEPUTADOS + "/" + URL_COMPLEMENT_NUMBER.ID_UNKNOWN_ERROR,
}

export enum PROPOSICOES_TRAMITACOES {
    SUCCESS = BASE_URL + API_URLS.PROPOSICOES + "/" + URL_COMPLEMENT_NUMBER.ID_SUCCESS,
    NOT_FOUND = BASE_URL + API_URLS.PROPOSICOES + "/" + URL_COMPLEMENT_NUMBER.ID_NOT_FOUND,
    UNKNOWN_ERROR = BASE_URL + API_URLS.PROPOSICOES + "/" + URL_COMPLEMENT_NUMBER.ID_UNKNOWN_ERROR,
}