name: Lint

on:
  push:
    branches:
      - main 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: PNPM 
        uses: pnpm/action-setup@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Format and lint check
        run: |
          pnpm install
          pnpm lint
