name: Unit tests

on:
  push:
    branches:
      - main 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PNPM 
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Run unit tests
        run: |
          pnpm install
          pnpm unit:ci
